module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.16

replace github.com/codahale/hdrhistogram => github.com/HdrHistogram/hdrhistogram-go v0.9.0

require github.com/nats-io/natscli v0.0.0-20201207130909-c15ad280ec4b
